### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by UntitledPoptart** [h0nde/roblox-maintenance-bypass#12]
How tf do i delete it because im waiting for roblox to be back up for me i deleted the .bat file but that didnt work. if you could make a video showing me how to delete it that would be helpful

**Comment by BashGuy10** [comment]
Navigate to the hosts file, open it in a text editor, and remove all lines with the IP of 128.116.119.4 and a Roblox domain. Should reset it.
I don't know if you have to do this, but you may have to flush the DNS using `ipconfig /flushdns` in the terminal

**Comment by UntitledPoptart** [comment]
how do i get to hosts file

**Comment by UntitledPoptart** [comment]
and im on windows

**Comment by idkxyz** [comment]
go to C:\Windows\System32\drivers\etc
> and im on windows

**Comment by idkxyz** [comment]
remember to open notepad as admin

**Comment by LowfiInaTrexSuit** [comment]
i don't get it ;-; I don't see lines with the number 128.116.119.4 could be that I'm using the wrong file

**Comment by 39p** [comment]
do `notepad C:\Windows\System32\drivers\etc\hosts` on the command line, send what you see.

**Comment by LowfiInaTrexSuit** [comment]
> do `notepad C:\Windows\System32\drivers\etc\hosts` on the command line, send what you see.

you mean in the file thing?

**Comment by 39p** [comment]
> > do `notepad C:\Windows\System32\drivers\etc\hosts` on the command line, send what you see.
> 
> you mean in the file thing?

no just open the command prompt on windows and type that, it opens your host file. Make sure the command prompt is ran by administrator so you can edit it

**Comment by LowfiInaTrexSuit** [comment]
> > > do `notepad C:\Windows\System32\drivers\etc\hosts` on the command line, send what you see.
> > 
> > 
> > you mean in the file thing?
> 
> yeah just post what you see, if you see bunch of ips for roblox, remove it whenever you want to or when roblox comes back up

![image](https://user-images.githubusercontent.com/90568774/139598733-82e6a74f-635a-4407-8bb0-6e6e67520a23.png)
idk you mean that?

**Comment by 39p** [comment]
> > > > do `notepad C:\Windows\System32\drivers\etc\hosts` on the command line, send what you see.
> > > 
> > > 
> > > you mean in the file thing?
> > 
> > 
> > yeah just post what you see, if you see bunch of ips for roblox, remove it whenever you want to or when roblox comes back up
> 
> ![image](https://user-images.githubusercontent.com/90568774/139598733-82e6a74f-635a-4407-8bb0-6e6e67520a23.png) idk you mean that?

Yeah that, since you don't have any ips it's removed from your systems somehow
