### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by Gowixx** [h0nde/roblox-maintenance-bypass#19]
What's your discord? I want to contact you.

**Comment by 1x6** [comment]
yoo ur ignas friend

**Comment by uhIgnacio** [comment]
h0nda#5774 ig

**Comment by Gowixx** [comment]
> h0nda#5774 ig

send your tag u i lost it after term lol

**Comment by uhIgnacio** [comment]
> > h0nda#5774 ig
> 
> send your tag u i lost it after term lol

Wumpus#0911
