### ISSUE TITLE
i think it's not working for me

### ISSUE THREAD

**Issue by LowfiInaTrexSuit** [h0nde/roblox-maintenance-bypass#20]
i think it's not working for me telling me i don't have access or smth

**Comment by uhIgnacio** [comment]
try use old version from commits

**Comment by CinnamonPhysicist** [comment]
You didn't run it as administrator

**Comment by LowfiInaTrexSuit** [comment]
> You didn't run it as administrator

i did

**Comment by uhIgnacio** [comment]
roblox is back

**Comment by LowfiInaTrexSuit** [comment]
> roblox is back

not for all

**Comment by LowfiInaTrexSuit** [comment]
it's still down for me that's why im trying to use the bypasser

**Comment by CinnamonPhysicist** [comment]
> 
> 
> > You didn't run it as administrator
> 
> i did

The script only shows "Access is denied." if you didn't run it as administrator. You didn't provide an error, so I guessed it was that. Try closing and reopening your browser if you're 100% sure it applied correctly.

**Comment by LowfiInaTrexSuit** [comment]
> > > You didn't run it as administrator
> > 
> > 
> > i did
> 
> The script only shows "Access is denied." if you didn't run it as administrator. You didn't provide an error, so I guessed it was that. Try closing and reopening your browser if you're 100% sure it applied correctly.

what does reopening the browser do like is it neccessary?

**Comment by LowfiInaTrexSuit** [comment]
+i can show you that i'm running it as admin (tho for me the admin prompt isn't showing up idk if that's normal but happens with some stuff)

**Comment by CinnamonPhysicist** [comment]
> +i can show you that i'm running it as admin

![image](https://user-images.githubusercontent.com/91788193/139599351-ef3b9fa4-8f3f-468a-9604-688209e0e412.png)
![image](https://user-images.githubusercontent.com/91788193/139599362-d391ad35-0f5e-4b69-bf28-b56974c3c0e5.png)

It's easier to help if you can show the error.

**Comment by CinnamonPhysicist** [comment]
If you can show the error it's easier to help.

**Comment by LowfiInaTrexSuit** [comment]
> If you can show the error it's easier to help.

idk i can show the command prompt but it's gonna be on german

**Comment by CinnamonPhysicist** [comment]
yes yes it's not a problem I know enough german

**Comment by LowfiInaTrexSuit** [comment]
> yes yes it's not a problem I know enough german

ok wait what to put into there again i forgot and can't find again xd

**Comment by CinnamonPhysicist** [comment]
If you opened a command prompt just copy all lines and paste them in.

**Comment by LowfiInaTrexSuit** [comment]
> If you opened a command prompt just copy all lines and paste them in.

ok nvm fixed it didn't do the thing with copying all lines into there. Thanks
