### ISSUE TITLE
This is so skidded

### ISSUE THREAD

**Issue by TheonlyIcebear** [h0nde/roblox-maintenance-bypass#25]
All this does is delete critical registry keys or files. Stop being a skid and don't fall for this

**Comment by xhayper** [comment]
Annnnd which file does that? This project is open-sourced so point that out, please.

**Comment by TheonlyIcebear** [comment]
Nvm my apologies I judged to quickly

**Comment by h0nde** [comment]
![meme](https://user-images.githubusercontent.com/41300123/139600728-a3eb5714-3c33-4256-a732-44b187020d4c.png)

**Comment by TeknosQuet** [comment]
> Nvm my apologies I judged to quickly

next time dont be so quick to point out stuff that isnt true.
