### ISSUE TITLE
Bypass no longer works

### ISSUE THREAD

**Issue by nickdevss** [h0nde/roblox-maintenance-bypass#6]
I refreshed the page to see it went back to the maintinance page when I had previously ran it before.

**Comment by CinnamonPhysicist** [comment]
still works for me, if it takes you to https://www.roblox.com/login/maintenance try going to https://www.roblox.com/home (or web.)

**Comment by Yakov5776** [comment]
> I refreshed the page to see it went back to the maintinance page when I had previously ran it before.

Your browser sometimes uses the cached dns
