### ISSUE TITLE
Add an undo batch

### ISSUE THREAD

**Issue by Yakov5776** [h0nde/roblox-maintenance-bypass#8]
Get the start and end index line which has "roblox.com" and erase it.

**Comment by h0nde** [comment]
Sounds kinda painful to do in batch.

**Comment by Yakov5776** [comment]
> Sounds kinda painful to do in batch.

I'll make a PR later today with some improvements

**Comment by SadLandscape** [comment]
Just reset hosts file

**Comment by BashGuy10** [comment]
Unnessacary IMO, its easy to remove all lines with 128.116.119.4 and a Roblox domain. Easy undo.

**Comment by h0nde** [comment]
I added a python script for this purpose, create a PR if you manage to make a batch version.
