### ISSUE TITLE
Any risk to this?

### ISSUE THREAD

**Issue by NelsonH75** [h0nde/roblox-maintenance-bypass#9]
Cause from what I can tell it changes dns

**Comment by Creaperhunter** [comment]
no it just editing hosts file

**Comment by NelsonH75** [comment]
So will this cause any danger or any side effects?

**Comment by Yakov5776** [comment]
> So will this cause any danger or any side effects?

No, it's safe and easy to revert

**Comment by Creaperhunter** [comment]
> So will this cause any danger or any side effects?

no its 100% safe to use

**Comment by NelsonH75** [comment]
> > So will this cause any danger or any side effects?
> 
> No, it's safe and easy to revert

How to revert

**Comment by glixzzy** [comment]
> > > So will this cause any danger or any side effects?
> > 
> > 
> > No, it's safe and easy to revert
> 
> How to revert

all you gotta do is remove the ip and name on windows/system32/etc/hosts file

**Comment by regginator** [comment]
128.116.119.4 is Roblox's IP, the batch file overrides roblox.com endpoints with that IP to directly access the Roblox API. It's safe.

**Comment by NelsonH75** [comment]
> > > > So will this cause any danger or any side effects?
> > > 
> > > 
> > > No, it's safe and easy to revert
> > 
> > 
> > How to revert
> 
> all you gotta do is remove the ip and name on windows/system32/drivers/etc/hosts file

Wait what, I cant
